version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PDM_NO_VENV=true
      - PYTHONPATH=/app
    command: bash -c "pdm install && pdm run uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "pnpm install && pnpm dev"