version: '3.8'

services:
  frontend:
    container_name: airsight-frontend
    image: ghcr.io/xeron2000/airsight-frontend:latest
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    container_name: airsight-backend
    image: ghcr.io/xeron2000/airsight-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./data/sql_app.db

volumes:
  sqlite_data:
    driver: local
